# Generated by Django 3.0.1 on 2020-02-21 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classblog',
            old_name='body',
            new_name='평가내용',
        ),
        migrations.RemoveField(
            model_name='classblog',
            name='title',
        ),
        migrations.AddField(
            model_name='classblog',
            name='강의명',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classblog',
            name='교수명',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classblog',
            name='작성자',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
