# Generated by Django 3.0.1 on 2020-02-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcrud', '0002_auto_20200221_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classblog',
            old_name='작성자',
            new_name='author',
        ),
    ]
