# Generated by Django 3.0.1 on 2020-02-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcrud', '0004_auto_20200221_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classblog',
            name='author',
        ),
    ]
