# Generated by Django 3.0.1 on 2020-02-21 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classcrud', '0006_classblog_작성자'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classblog',
            name='작성자',
        ),
        migrations.AddField(
            model_name='classblog',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
