# Generated by Django 3.0.1 on 2020-02-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classcrud', '0007_auto_20200221_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classblog',
            name='authors',
        ),
        migrations.AddField(
            model_name='classblog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
