# Generated by Django 3.0.1 on 2020-02-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcrud', '0008_auto_20200221_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classblog',
            name='user',
        ),
    ]
